name: datastore_sample
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.1 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  amplify_flutter: ^1.4.0
  amplify_auth_cognito: ^1.4.0
  amplify_api: ^1.4.0
  amplify_datastore:
    path: /Users/quaelija/code/forks/amplify-flutter/packages/amplify_datastore
  amplify_authenticator: ^1.4.0
  amplify_storage_s3: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
